name: Lighthouse Audit
on:
  pull_request:
    branches: [master]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Start server
        run: npm run start -- -p 3000 &

      - name: Wait for server
        run: |
          timeout 60 bash -c 'until curl -f -s http://localhost:3000; do 
            sleep 3
          done'

      - name: Test routes
        run: |
          curl -I http://localhost:3000
          curl -I http://localhost:3000/explorer
          curl -I http://localhost:3000/engineer

      - name: Create artifacts directory
        run: mkdir -p /tmp/artifacts

      - name: Run Lighthouse audit
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: "http://localhost:3000,http://localhost:3000"
          outputDirectory: /tmp/artifacts

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports
          path: /tmp/artifacts
