name: Lighthouse Audit

on:
  workflow_call:

jobs:
  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Start server
        run: npm run start &

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse and save reports
        run: |
          mkdir -p lhci-reports
          npx lhci collect \
            --url=http://localhost:3000 \
            --numberOfRuns=3 \
            --settings.chromeFlags="--headless" \
            --outputDir=lhci-reports
          # Optional: assertions can be skipped
          # npx lhci assert || echo "Assertions skipped"

      - name: Upload Lighthouse reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lhci-reports/

      - name: Post PR comment with report link
        uses: actions/github-script@v7
        with:
          script: |
            const reportUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/suites/${process.env.GITHUB_RUN_ID}/artifacts`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:bar_chart: Lighthouse report is ready! You can download and view it here: [Report Artifact](${reportUrl})`
            });
