name: CI Pipeline

on:
  pull_request:
    branches: [master]
  push:
    branches: ["**"]

jobs:
  steps:
    - name: Code Format Check
      uses: ./.github/workflows/format.yaml

    - name: Lighthouse Audit
      uses: ./.github/workflows/audit.yaml
