name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Run prettier check
  prettier:
    name: Prettier Check
    uses: ./.github/workflows/prettier.yaml

  # Run eslint check
  eslint:
    name: ESLint Check
    uses: ./.github/workflows/eslint.yaml

  # Run tests with coverage
  test:
    name: Run Tests
    uses: ./.github/workflows/test.yaml
    with:
      upload-coverage: true
      coverage-threshold: 80

  # Run security scans
  security:
    name: Security Scan
    uses: ./.github/workflows/security.yaml
    with:
      audit-level: moderate

  # Build only after quality checks pass
  build:
    name: Build Check
    uses: ./.github/workflows/build.yaml
    needs: [prettier, eslint, test]
    with:
      upload-artifacts: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      artifact-name: production-build