name: Code Quality

on:
  push:
    branches: ["**"]      
  pull_request:           

jobs:
  prettier:
    uses: ./.github/workflows/prettier.yaml

  eslint:
    uses: /.github/workflows/eslint.yaml

  build:
    uses: /.github/workflows/build.yaml
