name: Security Scan

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      audit-level:
        required: false
        type: string
        default: 'moderate'
        description: 'npm audit level: low, moderate, high, critical'

jobs:
  npm-audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=${{ inputs.audit-level }}

      - name: Generate audit report
        if: always()
        run: |
          npm audit --json > audit-report.json || true
          npm audit --audit-level=info > audit-summary.txt || true

      - name: Upload audit reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-reports
          path: |
            audit-report.json
            audit-summary.txt
          retention-days: 30

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate